### ISSUE TITLE
适配win2003 x64 sp2的问题

### ISSUE THREAD

**Issue by bfqymmt** [n9e/win-collector#1]
直接运行win-collector.exe，提示`不是有效的win32程序`。能发布一个适配的程序吗？

**Comment by freedomkk-qfeng** [comment]
golang 1.10.8 以后不再支持 winXP 和 win2003，详见 https://github.com/golang/go/wiki/Windows
可能需要在 golang 1.10.8 版本下编译，但需要所有依赖项都支持 go 1.10.8 才行。
考虑到 win2003 已经停止支持很久了，不单独为他适配了。
有兴趣的可以自己尝试编译一下，大家交流。
