### ISSUE TITLE
夜莺V3版本的win-collector 报错

### ISSUE THREAD

**Issue by u31s** [n9e/win-collector#14]
按照辉哥的视频设置了address.yml和win-collector.yml，使用nssm.exe托管服务，出现报错，如下图：
![win-cllector](https://user-images.githubusercontent.com/19942704/96395986-a142c000-11f8-11eb-8d93-87df36bdde30.png)
（之前夜莺V2使用的是2.1的collector，没有报错），换了几台机器（server 2016、windows 10），都是这样

**Comment by freedomkk-qfeng** [comment]
直接命令行运行呢？
看看有没有啥错误

**Comment by u31s** [comment]
1、logs/collector/目录下的文件没有任何错误
2、用nssm.exe remove win-collector服务，手工运行win-collectir.exe，报错如下图（同时logs/collector/目录下的文件没有任何错误）
![win-collector 配置](https://user-images.githubusercontent.com/19942704/96403429-f1c31900-120a-11eb-9f0a-db085db56b79.png)
![win-collector error](https://user-images.githubusercontent.com/19942704/96403436-f38cdc80-120a-11eb-8760-3427d5d59654.png)

**Comment by UlricQin** [comment]
api后面写成了中文冒号吧

**Comment by u31s** [comment]
辉哥提醒的对，stra和API后面的：写成中文冒号了，可以了，谢谢
![win-collector error1](https://user-images.githubusercontent.com/19942704/96404410-73b44180-120d-11eb-89f2-4a87515a2399.png)
