### ISSUE TITLE
0.3.0版本在windows 2012 R2 Datacenter上以nssm方式运行不起来

### ISSUE THREAD

**Issue by yzun** [n9e/win-collector#15]
0.3.0版本在windows 2012 R2 Datacenter上以nssm方式运行不起来
系统：
![image](https://user-images.githubusercontent.com/3615557/97251402-c364bf80-1842-11eb-9564-8126c6407137.png)
![image](https://user-images.githubusercontent.com/3615557/97251426-d24b7200-1842-11eb-8ace-ff9a2b573859.png)
日志里面未输出任何东西
![image](https://user-images.githubusercontent.com/3615557/97251473-e8593280-1842-11eb-9b85-7b9083de8f3f.png)
单独执行，发现是无法获取sn。需要把win-collector.yml中sn的脚本清空才行

**Comment by freedomkk-qfeng** [comment]
修改成能获取到 sn 的 shell 即可
0.3.1 新特性，现在如果 shell 内不含空格，会将其视作一个字符串直接 report ，不再调用 powershell
也可以用这个方法来直接 report 固定值
