### ISSUE TITLE
0.2.2 版本 部分客服端 proc.agent.alive 频繁检测不到

### ISSUE THREAD

**Issue by ConanAPTX** [n9e/win-collector#16]
![图片](https://user-images.githubusercontent.com/72903562/97531455-30b55380-19ef-11eb-83b2-31ec02e2eb9d.png)
![图片](https://user-images.githubusercontent.com/72903562/97531514-4e82b880-19ef-11eb-86fa-17d2b92f28c1.png)

**Comment by UlricQin** [comment]
通常是时间不同步导致的
