### ISSUE TITLE
identity支持自定义别名，端口监听可用

### ISSUE THREAD

**Issue by mhccj** [n9e/win-collector#2]
目前n9e的endpoint如果出现重复后，对象树中只能显示其中一个，为了避免出现这种情况，需要自定义别名，目前端口监听的逻辑是，先往 127.0.0.1 试一下，不通的话，往 identity 上面再测试下，所以需要麻烦骐哥改下

**Comment by freedomkk-qfeng** [comment]
0.2.1 版本已经修复这个问题
