### ISSUE TITLE
管理员权限直接运行 win-collector.exe 即可

### ISSUE THREAD

**Issue by newmain20** [n9e/win-collector#3]
管理员权限直接运行 win-collector.exe 即可中提到的 win-collector.exe 在哪里下载的

**Comment by UlricQin** [comment]
https://github.com/n9e/win-collector/releases

**Comment by ethansunqing** [comment]
直接在server 2008 64位上运行 就出现 不是有效的win3程序

**Comment by freedomkk-qfeng** [comment]
release 是在 go1.14 上编译的。由于 golang 1.14 在 windows 上最低要求 server 2008R2，因此如果低于这个版本的话，可能无法运行。

如果要支持的话，可能需要自行选用更低版本的 golang 编译，但由于依赖的库项未必支持，所以不一定可以成功，可以尝试看看

**Comment by nondevops** [comment]
> release 是在 go1.14 上编译的。由于 golang 1.14 在 windows 上最低要求 server 2008R2，因此如果低于这个版本的话，可能无法运行。
> 
> 如果要支持的话，可能需要自行选用更低版本的 golang 编译，但由于依赖的库项未必支持，所以不一定可以成功，可以尝试看看

那岂不是windows7 windows10 这些版本都不支持呀? @freedomkk-qfeng

**Comment by freedomkk-qfeng** [comment]
> > release 是在 go1.14 上编译的。由于 golang 1.14 在 windows 上最低要求 server 2008R2，因此如果低于这个版本的话，可能无法运行。
> > 如果要支持的话，可能需要自行选用更低版本的 golang 编译，但由于依赖的库项未必支持，所以不一定可以成功，可以尝试看看
> 
> 那岂不是windows7 windows10 这些版本都不支持呀? @freedomkk-qfeng

win7 需要 sp1，也就是 server2008r2 的那个内核。win10 肯定是支持的
