### ISSUE TITLE
[咨询] 如果windows服务器很多，都需要覆盖，可有什么好建议处理？

### ISSUE THREAD

**Issue by nondevops** [n9e/win-collector#5]
[咨询] 如果windows服务器很多，都需要覆盖，可有什么好建议处理？
[咨询] 如果windows服务器都已覆盖，后续要更新win-collector的版本，如何批量自动更新处理？

**Comment by freedomkk-qfeng** [comment]
用自己喜欢的批量工具呗
ansible ?

**Comment by nondevops** [comment]
> 用自己喜欢的批量工具呗
> ansible ?

如果agent去管理agent安装卸载升级,就跟open-falcon一样的,这种是不是更方便更合理一点诶?
