### ISSUE TITLE
windwos agent占用1G的内存是否正常

### ISSUE THREAD

**Issue by yimeng** [n9e/win-collector#9]
监控项使用默认安装，使用nssm 做成了windows服务。

![WechatIMG203](https://user-images.githubusercontent.com/1982337/91681730-e8f68500-eb81-11ea-9b2f-621cfd88102e.png)

**Comment by freedomkk-qfeng** [comment]
不是太正常。。不应该占这么多才对。。。
有开进程监控么，看看进程的采集周期多久？一个采集周期能覆盖掉进程采集的开销么

夜莺默认配置里的进程/端口采集周期貌似是 10秒，这个对进程比较多的win而言，有点短，可能采不过来
